"""
This Python module creates matrices represented by dictionary mappings.to perform the calculations to set
the appropriate weights in the final graph.

This file is Copyright (c) 2023 Anubha Joshi, Lisa Ye, Simran Vig, Iris Li
"""

import calculations
from data_class import Data
from python_ta.contracts import check_contracts
import python_ta
import doctest

@check_contracts
def create_user_genre_matrix(data: Data) -> dict[str, dict[str, float]]:
    """
    Returns a dictionary mapping of users to a dictionary mapping each genre to their compatibility
    score for that genre on a scale of 0.0 to 1.0

    Preconditions:
        - all([0.0 <= data.user_to_rating[anime][user] <= 1.0 for anime in data.user_to_rating[user]] for user in data.user_to_rating)
    """

    user_genre_compat_map = {}

    for user in data.user_to_rating:
        user_genre_compat_map[user] = {}

        for genre in data.genre_to_anime:
            compat = calculations.user_to_genre_compatibility(data.user_to_rating, data.anime_to_genre, genre, user)

            user_genre_compat_map[user][genre] = compat

    return user_genre_compat_map


@check_contracts
def create_genre_anime_matrix(data: Data, user_genre_compat_map: dict[str, dict[str, float]]) \
        -> dict[str, dict[str, float]]:
    """
    Returns a dictionary mapping of genre to a dictionary mapping each anime to their compatibility
    score for that anime on a scale of 0.0 to 1.0

    Preconditions:
        - user_genre_compat_map was generated by the function create_user_genre_matrix()
    """

    genre_anime_map = {}
    genre_count = 1

    anime_user_dict = data.get_anime_user_dict()

    for genre in data.genre_to_anime:

        print('Loaded for ' + str(genre_count) + ' / ' + str(len(data.genre_to_anime)) + ' genres')

        genre_anime_map[genre] = {}

        for anime in data.anime_to_genre:
            compat = calculations.anime_to_genre_compatibility(anime, genre, anime_user_dict,
                                                               user_genre_compat_map, data.user_to_rating,
                                                               data.anime_to_genre)

            genre_anime_map[genre][anime] = compat

        genre_count += 1

    return genre_anime_map


@check_contracts
def mat_mul_map(user_genre_map: dict[str, dict[str, float]], genre_anime_map: dict[str, dict[str, float]],
                anime_list: list[str], user_anime_rating: dict[str, dict[str, float]], user_limit: int) \
        -> dict[str, dict[str, float]]:
    """
    Takes the dictionary mapping(s) of user to genre compaibility and genre to anime compatibility, along with the list
    of all animes, and dictionary mapping of user rating for each anime and returns a dictionary mapping
    of each user up to user_limit number of users to either their direct rating for the anime or the
    of each user up to user_limit number of users to either their direct rating for the anime or the
    predicted score calculated by matrix multiplication.

    Preconditions:
        - user_genre_map was returned by create_user_genre_matrix()
        - genre_anime_map was returned by create_genre_anime_matrix()
        - all(user in user_anime_rating for user in user_genre_map)
        - all({genre in user_genre_map[user] for genre in genre_anime_map} for user in user_genre_map)
        - all({anime in genre_anime_map[genre] for anime in anime_list} for genre in genre_anime_map)
    """

    mat_mul = {}

    user_count = 1

    for user in user_genre_map:
        if user_count > user_limit:
            break
        mat_mul[user] = {}

        for anime in anime_list:

            sum_score = 0

            if anime in user_anime_rating[user]:
                mat_mul[user][anime] = user_anime_rating[user][anime]
                continue

            for genre in genre_anime_map:
                sum_score += (user_genre_map[user][genre] * genre_anime_map[genre][anime])

            sum_score /= len(genre_anime_map)
            mat_mul[user][anime] = sum_score

        print('Loaded for ' + str(user_count) + ' / ' + str(user_limit) +
              ' users')
        user_count += 1

    return mat_mul


if __name__ == '__main__':
    data1 = Data()
    user_genre = create_user_genre_matrix(data1)
    genre_anime = create_genre_anime_matrix(data1, user_genre)
    mat_mul_m = mat_mul_map(user_genre, genre_anime, list(data1.anime_to_genre.keys()),
                          data1.user_to_rating, 100)

    doctest.testmod(verbose=True)

    python_ta.check_all(config={
        'max-line-length': 120,
        'disable': ['E9992', 'E9997']
    })
